import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeaderComponent from "../components/header";
import GoodPortfolioContent from "../components/good_portfolio";
import DiversifyPortfolio from "../components/diversify_porfolio";
import { Reviews } from "@mui/icons-material";
import ReviewsComponent from "../components/reviews";
import FooterComponent from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fiber Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-w-full p-0 m-0">
        <HeaderComponent />
        <GoodPortfolioContent />
        <DiversifyPortfolio />
        <ReviewsComponent />
        <FooterComponent />
      </div>
    </div>
  );
}
