import Head from "next/head";
import SignupForm from "../components/signup_form";

export default function Signup() {
  return (
    <div>
      <Head>
        <title>Signup Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <SignupForm />
      </div>
    </div>
  );
}
